version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nativephp_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - electron

  electron:
    build:
      context: .
      dockerfile: Dockerfile.electron
    container_name: nativephp_electron
    restart: unless-stopped
    volumes:
      - .:/app
    network_mode: "host"
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
